version: "2.2"

networks:
  mifos:
    driver: bridge
services:
  tpp-client:
    image: harbor.flexcore.mx/flexcore/com.mx.mifos.openbanking.tpp-client.master
    mem_limit: 2048m
    volumes:
      - ./certificates/fullchain1.pem:/etc/ssl/certs/fullchain.pem
      - ./certificates/privkey1.pem:/etc/ssl/private/privkey.pem
      - ./certificates/fullchain1.pem:/usr/local/lsws/admin/conf/webadmin.crt
      - ./certificates/privkey1.pem:/usr/local/lsws/admin/conf/webadmin.key
    restart: always    
    ports:
      - "443:443"
      - "7080:7080"
    networks:
      - mifos  
